name: Azure WebApp Container Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the default branch 
on:
  pull_request:
    branches: [ main ]
    
env:
  IMG_URL: ghcr.io/kafekhalife/kafekhalife-test # update with application image URL 
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    # login to ghcr with action supplied by Azure
    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: $${{ secrets.CR_USR }}
        password: ${{ secrets.CR_PAT }}
    
    - name: 'Docker build & push to GitHub Packages'
      run: |
        echo IMAGE_NAME=${{ env.IMG_URL }}:${{ github.sha }}
        docker build . -t ${{ env.IMG_URL }}:${{ github.sha }}
        docker push ${{ env.IMG_URL }}:${{ github.sha }}

    # Leveraging action supplied by Azure 
    - uses: azure/webapps-deploy@v2
      with:
        app-name: kafekhalife-test
        publish-profile: ${{ secrets.KAFE_AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{ env.IMG_URL }}:${{ github.sha }}
