name: Azure WebApp Container Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the default branch
on:
  pull_request:
    branches: [ main ]
    
env:
  AZURE_WEBAPP_NAME: 'kafekhalife-test'   # set this to your application's name
  IMG_URL: 'ghcr.io/kafekhalife/kafekhalife-test' # update with application image URL 




jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.CR_USR }}
        password: ${{ secrets.CR_PAT }}

    - name: 'Build Test Image'
      run: |
        docker build . -t ghcr.io/kafekhalife/kafekhalife-test:${{ github.sha }}
        docker push ghcr.io/kafekhalife/kafekhalife-test:${{ github.sha }}
        
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'kafekhalife-test'
        publish-profile: ${{ secrets.KAFE_AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'ghcr.io/kafekhalife/kafekhalife-test:${{ github.sha }}'
