on:
    push:
      branches: [ master ]
    pull_request:
  env:
    IMG_URL: ghcr.io/kafekhalife/kafekhalife
  
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      
      - uses: Azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ secrets.CR_USR }}
          password: ${{ secrets.CR_PAT }}
      
      - run: |
          echo IMAGE=$IMG_URL
          docker build . -t $IMG_URL:${{ github.sha }}
          docker push $IMG_URL:${{ github.sha }}
        
      # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_K8S_CREDS }}'
          cluster-name: sk-gh-talk
          resource-group: k8s-testing
          
      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: ghcr.io
          container-registry-username: ${{ secrets.CR_USR }}
          container-registry-password: ${{ secrets.CR_PAT }}
          secret-name: demo-k8s-secret
  
      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/deployment.yml
          images: |
            IMG_URL:${{ github.sha }}
          imagepullsecrets: |
            demo-k8s-secret